<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bpkm extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mbpkm');
        $this->load->library(array('form_validation','template'));
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'bpkm/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'bpkm/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'bpkm/';
            $config['first_url'] = base_url() . 'bpkm/';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Mbpkm->total_rows($q);
        $bpkm = $this->Mbpkm->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'bpkm_data' => $bpkm,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->template->caplet('bpkm/bpkm_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Mbpkm->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'name' => $row->name,
	    );
           $this->template->caplet('bpkm/bpkm_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bpkm'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('bpkm/create_action'),
	    'id' => set_value('id'),
	    'name' => set_value('name'),
	);
       $this->template->caplet('bpkm/bpkm_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
	    );

            $this->Mbpkm->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('bpkm'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Mbpkm->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('bpkm/update_action'),
		'id' => set_value('id', $row->id),
		'name' => set_value('name', $row->name),
	    );
             $this->template->caplet('bpkm/bpkm_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bpkm'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
	    );

            $this->Mbpkm->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('bpkm'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Mbpkm->get_by_id($id);

        if ($row) {
            $this->Mbpkm->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('bpkm'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('bpkm'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('name', 'name', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Bpkm.php */
/* Location: ./application/controllers/Bpkm.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-26 18:56:29 */
/* http://harviacode.com */