<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Religion extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mreligion');
        $this->load->library(array('form_validation','template'));
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'religion/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'religion/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'religion/';
            $config['first_url'] = base_url() . 'religion/';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Mreligion->total_rows($q);
        $religion = $this->Mreligion->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'religion_data' => $religion,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->template->caplet('religion/religion_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Mreligion->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'religionCode' => $row->religionCode,
		'religionName' => $row->religionName,
	    );
           $this->template->caplet('religion/religion_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('religion'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('religion/create_action'),
	    'id' => set_value('id'),
	    'religionCode' => set_value('religionCode'),
	    'religionName' => set_value('religionName'),
	);
        $this->template->caplet('religion/religion_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

//        if ($this->form_validation->run() == FALSE) {
//            $this->create();
//        } else {
            $data = array(
		'religionCode' => $this->input->post('religionCode',TRUE),
		'religionName' => $this->input->post('religionName',TRUE),
	    );

            $this->Mreligion->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('religion'));
//        }
    }
    
    public function update($id) 
    {
        $row = $this->Mreligion->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('religion/update_action'),
		'id' => set_value('id', $row->id),
		'religionCode' => set_value('religionCode', $row->religionCode),
		'religionName' => set_value('religionName', $row->religionName),
	    );
            $this->template->caplet('religion/religion_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('religion'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

//        if ($this->form_validation->run() == FALSE) {
//            $this->update($this->input->post('id', TRUE));
//        } else {
            $data = array(
		'religionCode' => $this->input->post('religionCode',TRUE),
		'religionName' => $this->input->post('religionName',TRUE),
	    );

            $this->Mreligion->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('religion'));
//        }
    }
    
    public function delete($id) 
    {
        $row = $this->Mreligion->get_by_id($id);

        if ($row) {
            $this->Mreligion->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('religion'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('religion'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('religionCode', 'religioncode', 'trim|required');
	$this->form_validation->set_rules('religionName', 'religionname', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Religion.php */
/* Location: ./application/controllers/Religion.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-01 18:51:31 */
/* http://harviacode.com */