<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mcity extends CI_Model
{

    public $table = 'city';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {        
         $this->db->select('a.*, b.provinceName');
         $this->db->from('city a');
         $this->db->join('province b', 'a.cityProvinceId = b.id');
         $this->db->where('a.id', $id);
        return $this->db->get($this->table)->row();
        
        
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('cityName', $q);
	$this->db->or_like('cityProvinceId', $q);
	$this->db->or_like('cityDeleted', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
         $this->db->select('a.*, b.provinceName')
         ->from('city a')
         ->join('province b', 'a.cityProvinceId = b.id');
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function get_limit_data2($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('cityName', $q);
	$this->db->or_like('cityProvinceId', $q);
	$this->db->or_like('cityDeleted', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mcity.php */
/* Location: ./application/models/Mcity.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-26 19:04:25 */
/* http://harviacode.com */