<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Memployee extends CI_Model
{

    public $table = 'employee';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('deleted',0);
        return $this->db->get($this->table)->result();
    }
    
     function get_dropdown()
    {
         $this->db->select('id, firstName, lastName, costRate, (select userlevelId from users where employeeId = employee.id limit 1) as userlevelId');
            $this->db->from('employee');           
            $this->db->where('deleted',0);
            $this->db->order_by('firstName','ASC'); 
            $query = $this->db->get();
        if ($query->num_rows() > 0) 
            {
                 return $query->result();
            }
       // return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    
    
    function getData($limit, $start = 0, $q = NULL) {
       // $this->db->order_by($this->id, $this->order);
        //$this->db->like('id', $q);
	$this->db->limit($limit, $start);
        

         $this->db->select('a.*,b.employeeStatus,b.employeeStatusColors,c.positionName');
            $this->db->from('employee a'); 
            $this->db->join('employee_status b', 'b.id = a.employeeStatusId', 'left');
            $this->db->join('position c', 'c.id = a.positionId', 'left');
            //$this->db->join('employee c2', 'c2.id=a.managerId', 'left');             
            $this->db->order_by('a.updateDate','DESC'); 
            
        $query = $this->db->get();
        if ($query->num_rows() > 0) 
            {
                 return $query->result();
            }
    }
    
    public function getDropDown()
    {
         $this->db->select('id,firstname,lastname');
            $this->db->from('employee');      
             $this->db->where("deleted", 0);            
            $this->db->order_by('firstName','DESC'); 
            
        $query = $this->db->get();
        if ($query->num_rows() > 0) 
            {
                 return $query->result();
            }
    }
    
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    public function add_import($data_user){
       
        $this->db->insert($this->table, $data_user);
        
   }

}

/* End of file Memployee.php */
/* Location: ./application/models/Memployee.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-21 20:29:03 */
/* http://harviacode.com */