<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mengagement_detail extends CI_Model {

    public $table = 'engagementdetail';
    public $id = 'id';
    public $order = 'DESC';
    public $helper;

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    function replaceAll($engagementId, $array = []) {

        $this->deleteAll($engagementId);
        $count = count($array['employeeId']);
        $data = [];

        if ($count) {
            for ($i = 0; $i < $count; $i++) {
                $data[] = [
                    'engagementId' => $engagementId,
                    'employeeId' => $array['employeeId'][$i],
                    'budgetHour' => self::cleanFormat($array['budgetHour'][$i]),
                    'billingRate' => self::cleanFormat($array['subTotal'][$i]),
                    'costrate' => self::cleanFormat($array['costRate'][$i])
                ];
            }
        }
        if ($data)
            foreach ($data as $v) {
                $this->insert($v);
            }
    }

    function details($engagementId) {
        $query = $this->db->get_where($this->table, array('engagementId' => $engagementId));
        return $query->result();
    }

    function deleteAll($engagementId) {
        $this->db->delete($this->table, array('engagementId' => $engagementId));
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    static function cleanFormat($str) {
        $array = ['"', "'", ",", "."];
        return str_replace($array, "", $str);
    }

}

/* End of file Mengagement.php */
/* Location: ./application/models/Mengagement.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-03 17:06:57 */
/* http://harviacode.com */