<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mengagement_detail extends CI_Model {

    public $table = 'engagementdetail';
    public $id = 'id';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    function replaceAll($engagementId, $array = []) {
        $this->deleteAll($engagementId);
        $count = count($array['employeeId']);

        $data = [];

        if ($count) {
            for ($i = 0; $i < $count; $i++) {
                $data[] = [
                    'engagementId'=>$engagementId,
                    'employeeId'=>$array[$i]['employeeId'],
                    'budgetHour'=>$array[$i]['budgetHour'],
                    'billingRate'=>$array[$i]['subTotal'],
                    'costrate'=>$array[$i]['costRate']
                ];
            }
        }
        
        if($data)
            foreach ($data as $v){
                $this->insert($v);
            }
    }

    function deleteAll($engagementId) {
        $this->db->where($this->engagementId, $engagementId);
        $this->db->delete($this->table);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mengagement.php */
/* Location: ./application/models/Mengagement.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-03 17:06:57 */
/* http://harviacode.com */