<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mindustry extends CI_Model
{

    public $table = 'industry';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('entityId', $q);
	$this->db->or_like('industryName', $q);
	$this->db->or_like('industryDescription', $q);
	$this->db->or_like('deleted', $q);
	$this->db->or_like('updateDate', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
	$this->db->select('a.*,b.company_name');
        $this->db->join('entity b', 'a.entityId = b.id');
        $this->db->order_by('updateDate', 'DESC');
        $this->db->where('a.deleted', 0);
	$this->db->limit($limit, $start);
        return $this->db->get("industry a")->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mindustry.php */
/* Location: ./application/models/Mindustry.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-02 15:23:57 */
/* http://harviacode.com */