<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mnon_chargeable extends CI_Model
{

    public $table = 'non_chargeable';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    
    function get_limit_data2($limit, $start = 0, $q = NULL) {
	    $this->db->select('a.*,CONCAT(d.firstName," ",d.lastName) as fullname, e.leaveCode,e.leaveName');
        $this->db->join('employee d', 'a.employeeId = d.id');
        $this->db->join('leave e', 'a.leaveId = e.id');
        $this->db->order_by('updateDate', 'DESC');
	        $this->db->limit($limit, $start);
        return $this->db->get("non_chargeable a")->result();
    }
    
    function get_limit_data($limit, $start = 0, $q = NULL) {
          $this->db->select('a.*,CONCAT(b.firstName," ",b.lastName) as fullname, c.leaveCode,c.leaveName');          
            $this->db->join('employee b', 'a.employeeId = b.id');     
            $this->db->join('leave c', 'a.leaveId = c.id');
            $this->db->order_by('a.updateDate', 'DESC');
	        $this->db->limit($limit, $start);
        return $this->db->get("non_chargeable a")->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mnon_chargeable.php */
/* Location: ./application/models/Mnon_chargeable.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-29 12:09:58 */
/* http://harviacode.com */