<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mservice extends CI_Model
{

    public $table = 'service';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('serviceDeleted',0);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('a.*, b.company_name');
         $this->db->from('service a');
         $this->db->join('entity b', 'a.entityId = b.id');
         $this->db->where('a.id', $id);
        $query = $this->db->get();
        return $query->row();
        
    }
    
    // get total rows
    function total_rows($q = NULL) {
	$this->db->from($this->table);
        $this->db->where('serviceDeleted',0);
        return $this->db->count_all_results();
    }
    function total_rows2($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('entityId', $q);
	$this->db->or_like('serviceCode', $q);
	$this->db->or_like('serviceName', $q);
	$this->db->or_like('serviceDescription', $q);
	$this->db->or_like('serviceDeleted', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }
    function get_limit_data($limit, $start = 0, $q = NULL) {
         $this->db->select('a.*, b.company_name');      
         $this->db->join('entity b', 'a.entityId = b.id');
         $this->db->where('a.serviceDeleted', 0);
	$this->db->limit($limit, $start);
	$this->db->order_by('a.updateDate', 'DESC');
        $query = $this->db->get('service a');  
        return $query->result();
        
        
    }
    // get data with limit and search
    function get_limit_data2($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('entityId', $q);
	$this->db->or_like('serviceCode', $q);
	$this->db->or_like('serviceName', $q);
	$this->db->or_like('serviceDescription', $q);
	$this->db->or_like('serviceDeleted', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mservice.php */
/* Location: ./application/models/Mservice.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-26 19:15:21 */
/* http://harviacode.com */