<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Muserslist extends CI_Model
{

    public $table = 'users';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('entityId', $q);
	$this->db->or_like('userlevelId', $q);
	$this->db->or_like('avatar', $q);
	$this->db->or_like('employeeId', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('active', $q);
	$this->db->or_like('deleted', $q);
	$this->db->or_like('userCreate', $q);
	$this->db->or_like('createDate', $q);
	$this->db->or_like('userUpdate', $q);
	$this->db->or_like('updateDate', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
         $this->db->select('a.*, b.company_name, c.userlevel_name, d.firstName,d.lastName');
            //$this->db->from('users a');
            $this->db->join('entity b', 'a.entityId = b.id');
            $this->db->join('userlevel c', 'a.userlevelId = c.id');
            $this->db->join('employee d', 'a.employeeId = d.id');
            $this->db->where('a.active', 1);
            $this->db->limit($limit, 0);
            $this->db->order_by('a.updateDate', 'DESC');
        //cek apakah ada ba
      $query = $this->db->get('users a');
        if ($query->num_rows() > 0) {
            return $query->result();
        }
    }
    
    function get_limit_data2($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('entityId', $q);
	$this->db->or_like('userlevelId', $q);
	$this->db->or_like('avatar', $q);
	$this->db->or_like('employeeId', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('active', $q);
	$this->db->or_like('deleted', $q);
	$this->db->or_like('userCreate', $q);
	$this->db->or_like('createDate', $q);
	$this->db->or_like('userUpdate', $q);
	$this->db->or_like('updateDate', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Muserslist.php */
/* Location: ./application/models/Muserslist.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-26 20:45:47 */
/* http://harviacode.com */